"""inicial

Revision ID: 72f4163c967e
Revises: 
Create Date: 2026-09-07 22:48:58.404350
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=160), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cep', sa.String(length=12), nullable=True),
    sa.Column('municipio', sa.String(length=80), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('e_vendedora', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=True),
    sa.Column('renavam', sa.String(length=15), nullable=True),
    sa.Column('chassi', sa.String(length=25), nullable=True),
    sa.Column('numero_ordem', sa.String(length=10), nullable=True),
    sa.Column('marca_modelo', sa.String(length=80), nullable=True),
    sa.Column('ano_fab', sa.Integer(), nullable=True),
    sa.Column('ano_modelo', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.Column('especie', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('combustivel', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_veiculo_ordem', 'veiculo', ['numero_ordem'], unique=False)
    op.create_index(op.f('ix_veiculo_renavam'), 'veiculo', ['renavam'], unique=False)
    op.create_index('uq_veiculo_placa', 'veiculo', ['placa'], unique=True, postgresql_where=sa.text('placa IS NOT NULL'))
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=40), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=20), nullable=False),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('tipo_servico', sa.String(length=20), nullable=False),
    sa.Column('data_vistoria', sa.Date(), nullable=True),
    sa.Column('local', sa.String(length=80), nullable=True),
    sa.Column('despachante_id', sa.Integer(), nullable=True),
    sa.Column('formulario', sa.String(length=60), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['despachante_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.String(length=120), nullable=False),
    sa.Column('numero_nf', sa.String(length=30), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=160), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nota_data_emissao'), 'nota', ['data_emissao'], unique=False)
    op.create_table('processo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servico', sa.String(length=20), nullable=False),
    sa.Column('tipo_avulso', sa.String(length=80), nullable=True),
    sa.Column('data_recebimento', sa.Date(), nullable=False),
    sa.Column('prazo_dias', sa.Integer(), nullable=False),
    sa.Column('data_limite', sa.Date(), sa.Computed('data_recebimento + prazo_dias', persisted=True), nullable=False),
    sa.Column('etapa', sa.String(length=60), nullable=False),
    sa.Column('exigencia', sa.Text(), nullable=True),
    sa.Column('data_reagendamento', sa.Date(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('duda_tp', sa.String(length=20), nullable=True),
    sa.Column('data_venda', sa.Date(), nullable=True),
    sa.Column('numero_crv', sa.String(length=20), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('email_msg_id', sa.String(length=80), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processo_etapa'), 'processo', ['etapa'], unique=False)
    op.create_index(op.f('ix_processo_tipo_servico'), 'processo', ['tipo_servico'], unique=False)
    op.create_table('anexo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tipo_doc', sa.String(length=20), nullable=True),
    sa.Column('pagina_origem', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=True),
    sa.Column('lido', sa.Boolean(), nullable=False),
    sa.Column('criado_por', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('despesa', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_nota', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['nota.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processo_id'], ['processo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processo_id', name='uq_nota_item_processo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_item')
    op.drop_table('aviso')
    op.drop_table('anexo')
    op.drop_index(op.f('ix_processo_tipo_servico'), table_name='processo')
    op.drop_index(op.f('ix_processo_etapa'), table_name='processo')
    op.drop_table('processo')
    op.drop_index(op.f('ix_nota_data_emissao'), table_name='nota')
    op.drop_table('nota')
    op.drop_table('lote')
    op.drop_table('auditoria')
    op.drop_table('usuario')
    op.drop_index('uq_veiculo_placa', table_name='veiculo', postgresql_where=sa.text('placa IS NOT NULL'))
    op.drop_index(op.f('ix_veiculo_renavam'), table_name='veiculo')
    op.drop_index('ix_veiculo_ordem', table_name='veiculo')
    op.drop_table('veiculo')
    op.drop_table('empresa')
    # ### end Alembic commands ###
